# Creating the application

## Understanding Cells

In [2]:
from sklearn.datasets import load_boston
Boston = load_boston()
print(Boston.data.shape)

(506, 13)


In [4]:
myVar = 3 + 4
print(myVar)

7


In [6]:
print("This is myVar: ", myVar)

This is myVar:  7


# Introducing matrix in python

In [2]:
import numpy as np
myMatrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (myMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#Another matrix trick
myMatrix = np.ones([4,4], dtype=np.int32)
print (myMatrix)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [5]:
myMatrix = np.mat([[1,2,3], [4,5,6], [7,8,9]])
print (myMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Matrix multpilication

In [7]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
print (a*b)

[[ 1  4  9]
 [16 25 36]]


### Dot product

In [11]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (a.dot(b))

[[30 36 42]
 [66 81 96]]


### Reshape 

In [12]:
changeIt = np.array([1,2,3,4,5,6,7,8])
print(changeIt)
print(changeIt.reshape(2,4))
print (changeIt.reshape(2,2,2))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Also transposition

In [3]:
changeIt = np.array([[1,2,3,4], [5,6,7,8]])
print(changeIt)
print(np.transpose(changeIt))

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


## New Matrix Properties

In [4]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### Incldues inverting a matrix

In [8]:
a = np.array([[1,2], [3,4]])
b = np.linalg.inv(a)
print(np.allclose(np.dot(a,b), np.identity(2)))

True


# Example
#### What this example shows is a vector input (tensors) that go through an algorithm (math to encode inputs into a more recognizable form) so that we may observe new patterns in the data to best interpret a solution

In [11]:
inputs = np.array([5,10,15])
weights = np.array([[.5,.2,-1], [.3,.4,.1], [-.2,.1,.3]])
results = np.dot(inputs, weights)
print (results)

[2.5 6.5 0.5]


# Vectorization
## Doing multiple math operations of the same kind at once

In [12]:
# This is actually pretty cool, doAdd and vectAdd are both functions... we call vect add on the two vectors which
# Scales up the do add function to accept for inputs. All of the math is done simultaniously in one call
# Rather than having to loop through and do each add individually... can be a big time saver
def doAdd(a,b):
    return a+b
vectAdd = np.vectorize(doAdd)
print(vectAdd([1,2,3,4],[1,2,3,4]))

[2 4 6 8]
